set(CMAKE_C_COMPILER zig cc)
set(CMAKE_CXX_COMPILER zig c++)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -target ${ZIG_TARGET}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -target ${ZIG_TARGET}")

set(CMAKE_C_LINKER_DEPFILE_SUPPORTED FALSE)
set(CMAKE_CXX_LINKER_DEPFILE_SUPPORTED FALSE)

set(CMAKE_C_ARCHIVE_CREATE "zig ar qc <TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_APPEND "zig ar r <TARGET> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "zig ranlib <TARGET>")

set(CMAKE_CXX_ARCHIVE_CREATE "zig ar qc <TARGET> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_APPEND "zig ar r <TARGET> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH "zig ranlib <TARGET>")